# Generated by Django 4.0.6 on 2022-07-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rahbariyat',
            name='rahbar_rasmi',
            field=models.ImageField(upload_to='uploads/images'),
        ),
    ]
