# Generated by Django 4.0.6 on 2022-07-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_rahbariyat_rahbar_rasmi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xodim_nomi', models.CharField(max_length=255)),
                ('lavozimi', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='rahbariyat',
            name='rahbar_rasmi',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
