# Generated by Django 4.0.6 on 2022-07-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_tadbirlar_img_2_alter_tadbirlar_img_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rahbariyat',
            name='tugulgan_sanasi',
            field=models.DateField(),
        ),
    ]
