# Generated by Django 4.0.6 on 2022-07-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_rahbariyat_tugulgan_sanasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rahbariyat',
            name='tugulgan_sanasi',
            field=models.DateField(),
        ),
    ]
