# Generated by Django 4.0.6 on 2022-07-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_rahbariyat_tugulgan_sanasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('sarlavha', models.CharField(max_length=255)),
                ('tavsifi', models.TextField(blank=True, null=True)),
                ('yaratilish_vaqti', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tadbirlar',
            name='yangilaninsh_vaqti',
        ),
    ]
