# Generated by Django 4.0.6 on 2022-07-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_elonlar_remove_tadbirlar_yangilaninsh_vaqti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qonunlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.FilePathField()),
            ],
        ),
    ]
