# Generated by Django 4.0.6 on 2022-07-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_qonunlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qonunlar',
            name='nomi',
            field=models.FileField(upload_to='images/'),
        ),
    ]
