# Generated by Django 4.0.6 on 2022-07-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_qonunlar_nomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='qonunlar',
            name='file',
            field=models.FileField(default='', upload_to='file/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qonunlar',
            name='nomi',
            field=models.CharField(max_length=500),
        ),
    ]
