# Generated by Django 4.0.6 on 2022-07-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_qonunlar_file_alter_qonunlar_nomi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asosiy_Rasimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_1', models.ImageField(upload_to='images/')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
