# Generated by Django 4.0.6 on 2022-07-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_biz_haqimizda'),
    ]

    operations = [
        migrations.AddField(
            model_name='biz_haqimizda',
            name='img_1',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biz_haqimizda',
            name='img_2',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
