# Generated by Django 4.0.6 on 2022-07-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_biz_haqimizda_img_1_biz_haqimizda_img_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='file/')),
            ],
        ),
    ]
